version: '3.0'

networks:
  app:
    driver: bridge

volumes:
  db-grpc-data:
    driver: local
  redis-grpc-data:
    driver: local

services:
  generator:
    platform: linux/amd64
    image: 'kkozlovsky/data-generator-grpc-microservice:latest'
    networks:
      - app
    depends_on:
      - postgres
      - analyzer
    environment:
      - GRPC_HOST=analyzer:${GRPC_PORT}
      - BATCH_SIZE=${GENERATOR_BATCH_SIZE}
    ports:
      - '8081:8081'

  analyzer:
    platform: linux/amd64
    image: 'kkozlovsky/data-analyzer-grpc-microservice:latest'
    networks:
      - app
    depends_on:
      - postgres
    environment:
      - GRPC_PORT=${GRPC_PORT}
      - HOST=${HOST}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
    ports:
      - '8082:8082'

  store:
    platform: linux/amd64
    image: 'kkozlovsky/data-store-grpc-microservice:latest'
    networks:
      - app
    depends_on:
      - postgres
    environment:
      - GRPC_HOST=analyzer:${GRPC_PORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - BATCH_SIZE=${STORE_BATCH_SIZE}
    ports:
      - '8083:8083'

  postgres:
    image: 'postgres:15.1-alpine'
    networks:
      - app
    env_file:
      - .env
    ports:
      - '5437:5432'
    volumes:
      - db-grpc-data:/var/lib/postgresql/data

  redis:
    image: redis:7.2-rc-alpine
    networks:
      - app
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - redis-grpc-data:/data